version: '3.8'

networks:
  db_net:
    driver: bridge

volumes:
  data_db:

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PWD}
      MYSQL_USER: ${DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PWD}
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    volumes:
      - data_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links: 
      - mysql-db
    ports:
      - 8080:80
    depends_on:
      - mysql-db
    restart: always  
    environment:
     PMA_HOST: mysql-db
     PMA_PASSWORD: teste@1234
      
          
    
